### ISSUE TITLE
PA:Review Frontend Auth Demo

### ISSUE THREAD

**Issue by wongshington** [wongshington/QuickStarter#13]
functional demo/guest login in button

**Comment by s-pangburn** [comment]
### Things to fix

1. Replace the headers with the logo, I think it will look better than the all-caps titles you have now (that or style the title to look more like a header). You could also have the logo in addition to the captions, but style the captions to look coherent with the logo.

2. Add more padding to the top and bottom of the modal. Whitespace is your friend. Take a look at other sites with modals and see how they space out their content?

3. Since you have a modal, make sure there is a link in the modal to switch between the login and signup forms.

4. Would prefer you change the "Close" to a big "X". Just more conventional.

5. Errors should display in red or gray or some other color than the default. Also they need more padding around them.

6. The modal should probably be higher up on the page, and I think it's a little off-center. The signup modal in particular looks like it's too low.

7. "Demo" should be something more descriptive, like "Demo Login". Right now it's not clear what it does to a user that doesn't know what to expect. Might also work better on the form itself, but if you don't have time for that, having it in the top bar is perfectly fine.

8. When you sign up the modal doesn't close. Same when you login.

9. It's a little weird to set a username and still log in with your email. I think more people would remember their username, so prioritize logging in with that instead.

10. Would prefer for "Sign Out" to be all the way at the right of the navbar instead of leaving that whitespace after it.

11. Also, increase padding on the top and bottom of the navbar, as we discussed before.

Okay, that looks like a lot, but most of it is small styling fixes. Do your best with these and get back to me when you'd like me to take another look!

**Comment by s-pangburn** [comment]
Looks good! Issue closed.
